import type { Metadata } from 'next';
import { ClerkProvider, Show, SignInButton, SignUpButton } from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import './global.css';
import { ClerkApolloProvider } from './components/Apollo-provider';
import { RoleGuard } from './components/RoleGuard';
import { Toaster } from '@erkhes-monorepo/shadcn';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider>
          <Show when="signed-out">
            <SignInButton />
            <SignUpButton>
              <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                Sign Up
              </button>
            </SignUpButton>
          </Show>

          <ClerkApolloProvider>
            <RoleGuard>
              {children}
              <Toaster />
            </RoleGuard>
          </ClerkApolloProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
